/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AudioDevice {
  id: string
  name: string
  deviceType: string
  channels: number
  defaultSampleRate: number
  hostApi: string
  isDefault: boolean
}
/** List all available audio devices on the system. */
export declare function listDevices(): Array<AudioDevice>
/**
 * Start system audio loopback capture.
 *
 * @param deviceId  WASAPI endpoint ID (use "default" for default render device)
 * @param sampleRate  Target sample rate in Hz (e.g. 16000 for STT)
 * @param channels  Target channels (1 = mono)
 * @param callback  JS function called with each PCM chunk as Buffer (16-bit int LE)
 * @returns Handle number — pass to stopLoopback() to stop
 */
export declare function startLoopback(deviceId: string, sampleRate: number, channels: number, callback: (arg: Array<number>) => any): number
/**
 * Stop a running loopback capture.
 *
 * @param handle  The handle returned by startLoopback()
 */
export declare function stopLoopback(handle: number): void
/**
 * Start microphone (input device) capture.
 *
 * @param deviceId  WASAPI endpoint ID (use "default" for default input device)
 * @param sampleRate  Target sample rate in Hz (e.g. 16000)
 * @param channels  Target channels (1 = mono)
 * @param callback  JS function called with each PCM chunk as Buffer (16-bit int LE)
 * @returns Handle number — pass to stopMicCapture() to stop
 */
export declare function startMicCapture(deviceId: string, sampleRate: number, channels: number, callback: (arg: Array<number>) => any): number
/**
 * Stop a running mic capture.
 *
 * @param handle  The handle returned by startMicCapture()
 */
export declare function stopMicCapture(handle: number): void
/** Get the native module version. */
export declare function getVersion(): string
